# Generated by Django 2.2.6 on 2020-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='total_cases',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='total_deaths',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='total_recovered',
        ),
        migrations.AddField(
            model_name='cases',
            name='no_of_test',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
